openapi: 3.0.3
info:
  title: Mercury
  version: 0.1.1
servers:
  - url: http://localhost:8000
    description: Local

paths:
  /candidate_labels:
    get:
      summary: Get candidate labels
      description: Get candidate labels for labeling
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LabelMeta"

  /user/me:
    get:
      summary: Get current user info
      description: Get current user info
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HTTPException"
      security:
        - OAuth2: []

  /user/name:
    post:
      summary: Update current user name
      description: Update current user name
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RequestMessage"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HTTPException"
      security:
        - OAuth2: []

  /user/export:
    get:
      summary: Export labels made by current user
      description: Export labels made by current user
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/LabelData"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HTTPException"
      security:
        - OAuth2: []

  /task:
    get:
      summary: Get task count
      description: Get task count
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  all:
                    type: integer

  /task/{task_index}:
    get:
      summary: Get task info
      description: Get task info
      parameters:
        - name: task_index
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: "#/components/schemas/Task"
                  - $ref: "#/components/schemas/RequestError"

  /task/{task_index}/history:
    get:
      summary: Get all labels made for a task
      description: Get all labels made for a task
      parameters:
        - name: task_index
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/LabelData"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HTTPException"
      security:
        - OAuth2: []

  /task/{task_index}/label:
    post:
      summary: Submit a label for a task
      description: Submit a label for a task
      parameters:
        - name: task_index
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Label"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RequestMessage"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HTTPException"
      security:
        - OAuth2: []

  /task/{task_index}/label/{record_id}:
    patch:
      summary: Edit a label for a task
      description: Edit a label for a task
      parameters:
        - name: task_index
          in: path
          required: true
          schema:
            type: integer
        - name: record_id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Label"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RequestMessage"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HTTPException"
        "403":
          description: Not allowed to edit other's annotation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HTTPException"
        "404":
          description: Annotation not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HTTPException"
      security:
        - OAuth2: []

  /task/{task_index}/select:
    post:
      summary: Get AI prediction for a selected span
      description: Get AI prediction for a selected span. Returns five possible spans.
      parameters:
        - name: task_index
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Selection"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                oneOf:
                  - type: array
                    items:
                      $ref: "#/components/schemas/SelectionResponseSlice"
                  - $ref: "#/components/schemas/RequestError"

  /annot/{annot_index}/comments:
    parameters:
      - name: annot_index
        in: path
        required: true
        schema:
          type: integer

    get:
      summary: Get all comments for a label
      description: Get all comments for a label
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Comment"
    post:
      summary: Submit a comment for a label
      description: Submit a comment for a label
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CommentData"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RequestMessage"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HTTPException"
      security:
        - OAuth2: []

  /annot/{annot_index}/comments/{comment_id}:
    parameters:
      - name: annot_index
        in: path
        required: true
        schema:
          type: integer
      - name: comment_id
        in: path
        required: true
        schema:
          type: integer

    patch:
      summary: Edit a comment for a label
      description: Edit a comment for a label
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CommentData"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RequestMessage"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HTTPException"
        "403":
          description: Not allowed to edit other's comment
      security:
        - OAuth2: []

    delete:
      summary: Delete a comment for a label
      description: Delete a comment for a label
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RequestMessage"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HTTPException"
        "403":
          description: Not allowed to delete other's comment
      security:
        - OAuth2: []

  /record/{record_id}:
    delete:
      summary: Delete a label
      description: Delete a label
      parameters:
        - name: record_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RequestMessage"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HTTPException"
        "403":
          description: Not allowed to delete other's annotation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HTTPException"
      security:
        - OAuth2: []

components:
  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        password:
          tokenUrl: /login
  schemas:
    HTTPException:
      type: object
      properties:
        detail:
          type: string

    RequestMessage:
      type: object
      properties:
        message:
          type: string

    RequestError:
      type: object
      properties:
        error:
          type: string

    User:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        email:
          type: string

    LabelMeta:
      type: array
      items:
        oneOf:
          - type: string
          - type: object
            properties:
              LABEL:
                type: array
                items:
                  type: string

    LabelData:
      type: object
      required:
        - record_id
        - sample_id
        - summary_start
        - summary_end
        - source_start
        - source_end
        - consistent
        - task_index
        - user_id
        - note
      properties:
        record_id:
          type: integer
        sample_id:
          type: string
        summary_start:
          type: integer
        summary_end:
          type: integer
        source_start:
          type: integer
        source_end:
          type: integer
        consistent:
          type: array
          items:
            type: string
        task_index:
          type: integer
        user_id:
          type: string
        note:
          type: string
        username:
          type: string

    Label:
      type: object
      properties:
        summary_start:
          type: integer
        summary_end:
          type: integer
        source_start:
          type: integer
        source_end:
          type: integer
        consistent:
          type: array
          items:
            type: string
        note:
          type: string

    Task:
      type: object
      properties:
        doc:
          type: string
        sum:
          type: string

    Selection:
      type: object
      properties:
        start:
          type: integer
        end:
          type: integer
        from_summary:
          type: boolean

    SelectionResponseSlice:
      type: object
      properties:
        score:
          type: number
        offset:
          type: integer
        len:
          type: integer
        to_doc:
          type: boolean

    Comment:
      type: object
      properties:
        comment_id:
          type: integer
        user_id:
          type: string
        username:
          type: string
        annot_id:
          type: integer
        parent_id:
          type: integer
          nullable: true
        text:
          type: string
        comment_time:
          type: string

    CommentData:
      type: object
      required:
        - annot_id
        - text
      properties:
        annot_id:
          type: integer
        parent_id:
          type: integer
          nullable: true
        text:
          type: string
